export {
  IconLayoutDashboard as DashboardIcon,
  IconUsers as LeadsIcon,
  IconBriefcase as DealsIcon,
  IconBuilding as CustomersIcon,
  IconChartBar as ReportsIcon,
  IconSettings as UsersIcon,
  IconLogout as LogoutIcon,
  IconChevronRight as ChevronRightIcon,
  IconMenu2 as MenuIcon,
  IconPlus as PlusIcon,
  IconPencil as EditIcon,
  IconTrash as DeleteIcon,
  IconSearch as SearchIcon,
  IconFilter as FilterIcon,
  IconTrendingUp as TrendingUpIcon,
  IconTrendingDown as TrendingDownIcon,
  IconCurrencyDollar as RevenueIcon,
  IconTarget as TargetIcon,
  IconUserCheck as UserCheckIcon,
  IconAlertCircle as AlertIcon,
  IconCheck as CheckIcon,
  IconLoader2 as LoadingIcon,
  IconEye as EyeIcon,
  IconMail as MailIcon,
  IconPhone as PhoneIcon,
  IconMapPin as LocationIcon,
  IconCalendar as CalendarIcon,
  IconRefresh as RefreshIcon,
  IconDotsVertical as MoreIcon,
  IconArrowUp as ArrowUpIcon,
  IconArrowDown as ArrowDownIcon,
  /* shadcn/ui & layout */
  IconBell as BellIcon,
  IconChevronDown as ChevronDownIcon,
  IconChevronUp as ChevronUpIcon,
  IconLayoutSidebarLeftCollapse as PanelLeftIcon,
  IconLayoutGrid as LayoutGridIcon,
} from "@tabler/icons-react"

export { IconX as CloseIcon, IconX as XIcon } from "@tabler/icons-react"
